api/app.py
""" This module contains the flask app """
from os import environ
from dotenv.main import load_dotenv
from flask import (
    Flask,
    make_response,
    jsonify,
)
from flask_cors import CORS
from models import storage
from api.views import app_views


app = Flask(__name__)
app.config['SECRET_KEY'] = environ.get('SECRET_KEY')
origins = '*'


CORS(
    app,
    resources={r"/*": {"origins": origins}},
    supports_credentials=True
)


app.register_blueprint(app_views)


@app.teardown_appcontext
def close_db(err):
    """ Closes the storage session on an error """
    storage.close()


@app.errorhandler(404)
def not_found(err):
    """ Handles 404 errors """
    response = make_response(jsonify({'Error': 'Not Found'}), 404)
    return response


if __name__ == '__main__':
    load_dotenv()
    app.run(
        host='0.0.0.0',
        port=environ.get('VEDA_PORT', default='8080'),
        threaded=True)

api/views/__init__.py
""" This module contains the blueprint for the API """
from flask import Blueprint


app_views = Blueprint('app_views', __name__, url_prefix='/api/')


from api.views.index import *  # noqa: E402
from api.views.students import *  # noqa: E402
from api.views.attendances import *  # noqa: E402

api/views/index.py
""" This module contains the index view """
import csv

from api.views import app_views
from flask import jsonify, render_template, send_file
from models import storage
from api.views.attendances import attendance_sheet


@app_views.route('/status', methods=['GET'])
def status():
    """ Returns the status of the API """
    return jsonify({'status': 'OK'})


@app_views.route('/stats', methods=['GET'], strict_slashes=False)
def stats():
    """ Returns the stats of the API """
    return jsonify({
        'students': storage.count('Student'),
        'attendances': storage.count('Attendance'),
    })


@app_views.route('/', methods=['GET'], strict_slashes=False)
def index():
    """ Returns the index of the API """

    sheets = attendance_sheet()[0].json
    
    unique_dates = set()
    
    # Loop through the sheets and add dates to the set
    for sheet in sheets:
        for attendance in sheet['attendance']:
            unique_dates.add(attendance['date'])

    return render_template('index.html', sheets=sheets, unique_dates=sorted(unique_dates))


@app_views.route('/sheet', methods=['GET'], strict_slashes=False)
def sheet():
    """ Returns the sheet as a csv to download """

    sheets = attendance_sheet()[0].json
    csv_file = "attendance.csv"

    # Write JSON data to a CSV file
    with open(csv_file, mode='w', newline='') as file:
        writer = csv.writer(file)

        # Write header row
        dates = set()
        for student in sheets:
            for attendance in student["attendance"]:
                dates.add(attendance["date"])
        dates = sorted(dates)
        rows = ["id", "first_name", "last_name", "matric_number"]
        rows.extend(dates)
        end = ["score", "percentage"]
        rows.extend(end)
        writer.writerow(rows)

        # Iterate through the JSON data and write to the CSV file
        for student in sheets:
            total = 0
            newRow = [student["id"], student["first_name"], student["last_name"], student["matric_number"]]
            for date in dates:
                for record in student["attendance"]:
                    if record["date"] == date:
                        newRow.append(1)
                        total += 1
                        break
                else:
                    newRow.append(0)
            newRow.append(total)
            percentage = (total / len(dates)) * 100
            newRow.append(round(percentage, 2))

            writer.writerow(newRow)

    return send_file(csv_file, as_attachment=True)

api/views/students.py
""" This module contains the student view """

from flask import (
    jsonify,
    request,
    abort,
    make_response
)

from api.views import app_views
from models import storage
from models.attendance import Attendance
from models.student import Student


@app_views.route('/students', methods=['GET'], strict_slashes=False)
def get_students():
    """ Returns all students """
    students = storage.all('Student')
    return jsonify([user.to_dict() for user in students.values()])


@app_views.route('/students/<student_id>', methods=['GET'], strict_slashes=False)
def get_student(student_id):
    """ Returns a student """
    student = storage.get('Student', student_id)
    if not student:
        abort(404, 'Student does not exist')
    return jsonify(student.to_dict())


@app_views.route('/students/<student_id>', methods=['DELETE'], strict_slashes=False)
def delete_student(student_id):
    """ Deletes a student """
    student = storage.get('Student', student_id)
    if not student:
        abort(404, 'Student does not exist')
    storage.delete(student)
    return jsonify({}), 200


@app_views.route('/students', methods=['POST'], strict_slashes=False)
def post_student():
    """ Creates a new student """
    data = request.get_json()
    if not data:
        abort(400, 'Not a JSON')
    if 'id' not in data:
        abort(400, 'Missing id')
    student = Student(**data)
    storage.add(student)
    if 'matric_number' in data:
        with storage.session_scope() as session:
            existing_student = session.query(Student).filter(
                Student.matric_number == data['matric_number'],Student.id != data['id']).first()
            if existing_student:
                student = session.merge(student)
                setattr(student, 'first_name', existing_student.first_name)
                setattr(student, 'last_name', existing_student.last_name)
                attendances = session.query(Attendance).filter(
                    Attendance.student_id == existing_student.id
                ).all()
                for attendance in attendances:
                    setattr(attendance, 'student_id', student.id)
                    session.add(attendance)
                    session.commit()
                storage.add(student)
                storage.delete(existing_student)
    response = make_response(jsonify(student.to_dict()), 201)
    return response


@app_views.route('/students', methods=['PUT'], strict_slashes=False)
def put_student():
    """ Updates a student """
    data = request.get_json()
    if not data:
        abort(400, 'Not a JSON')
    if 'id' not in data:
        abort(400, 'Missing id')
    student = storage.get('Student', data['id'])
    if not student:
        print("Student does not exist")
        abort(404, 'Student does not exist')
    for key, value in data.items():
        setattr(student, key, value)
    storage.add(student)

    return jsonify(student.to_dict()), 200


@app_views.route('/students', methods=['DELETE'], strict_slashes=False)
def delete_all_students():
    """ Deletes a student """
    storage.drop()
    return jsonify({}), 200


@app_views.route(
    '/students/<student_id>/attendance',
    methods=['GET'],
    strict_slashes=False)
def get_student_attendance(student_id):
    """ Returns all attendance for a student """
    student = storage.get('Student', student_id)
    if not student:
        abort(404, 'Student does not exist')
    with storage.session_scope() as session:
        student = session.merge(student)
        attendance = [attendance.to_dict() for attendance in student.attendances]

    return jsonify(attendance)

api/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>Student Attendance</title>
    <!-- Meta Tags -->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta
      name="description"
      content="A biometric attendance system using R307 and Arduino."
    />
    <meta
      name="keywords"
      content="Arduino, R307, Biometric Attendance, Student Attendance"
    />
    <meta name="author" content="Aina Jesulayomi" />

    <!-- Include Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <div class="container">
      <div class="text-center bg-light p-5">
        <img src="{{ url_for('static', filename='funaablogo.webp') }}" alt="" class="img-fluid mr-3" style="max-height: 50px">
        <h1 class="display-4 text-primary">
          FUNAAB Student Attendance System
        </h1>
        <p class="text-secondary">
          Leveraging Biometrics for efficient attendance management
        </p>
      </div>
      <table class="table table-bordered table-striped">
        <thead class="thead-dark">
          <tr>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Matric Number</th>
            <!-- Loop through unique dates and display them in the table header -->
            {% for date in unique_dates %}
            <th>{{ date }}</th>
            {% endfor %}
            <th>Edit</th>
          </tr>
        </thead>
        <tbody>
          <!-- Loop through each student in the sheets variable -->
          {% for sheet in sheets %}
          <tr id="{{ sheet.id }}">
            <td>{{ sheet.id }}</td>
            <td class="first_name">{{ sheet.first_name }}</td>
            <td class="last_name">{{ sheet.last_name }}</td>
            <td class="matric_number">{{ sheet.matric_number or '-' }}</td>
            <!-- Loop through the dates and display 'present' or '-' -->
            {% for date in unique_dates %} {% set attendance = sheet.attendance
            | selectattr('date', 'eq', date) | first %}
            <td>
              {% if attendance and attendance.present %} {{ attendance.time }}
              {% else %} - {% endif %}
            </td>
            {% endfor %}
            <td class="d-flex justify-content-evenly"><button class="btn btn-primary edit-btn">Edit</button></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <!-- Button to download csv file -->
      <div class="text-center">
        <a href="{{ url_for('app_views.sheet') }}" class="btn btn-primary">Download Attendance sheet</a>
      </div>
    </div>

    <!-- Footer -->
    <footer class="footer mt-auto py-3 bg-dark text-white sticky-footer">
      <div class="container" style="min-width: 95%;">
        <div class="row">
          <div class="col-3">
            <span>Copyright &copy; 2023 Jesulayomi Aina Michael</span>
            <span><a href="https://github.com/Jesulayomy/Veda" target="_blank">GitHub</a></span>
          </div>
          <div class="col-6 text-center">
            <span>In partial fulfilment of the requirements for the award of B.Eng. degree in Electrical and Electronics Engineering, FUNAAB </span>
          </div>
          <div class="col-3">
            <span class="row">Supervisor: Dr. O. I. Adebisi</span>
            <span class="row">Head of Department: Dr. K. A. Amusa</span>
        </div>
      </div>
    </footer>

    <!-- CSS -->
    <style>
      body {
        display: flex;
        flex-direction: column;
        min-height: 100vh;
      }

      .sticky-footer {
        margin-top: auto;
      }
    </style>

    <!-- Include Bootstrap JS and jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
      crossorigin="anonymous"
    ></script>

    <!-- Include your custom script -->
    <script>
      $(document).ready(function () {
        $('table').on('click', '.edit-btn', function () {
          var tr = $(this).closest('tr');
          var id = tr.attr('id');
          var first_name = tr.find('.first_name').text();
          var last_name = tr.find('.last_name').text();
          var matric_number = tr.find('.matric_number').text();
    
          tr.data('original', {first_name: first_name, last_name: last_name, matric_number: matric_number});

          tr.find('.first_name').html(
            '<input type="text" id="first_name" value="' + first_name + '">'
          );
          tr.find('.last_name').html(
            '<input type="text" id="last_name" value="' + last_name + '">'
          );
          tr.find('.matric_number').html(
            '<input type="text" id="matric_number" value="' +
              matric_number +
              '">'
          );
    
          $(this)
            .parent()
            .html(
              '<button class="btn btn-success submit-btn mr-2">Submit</button><button class="btn btn-danger cancel-btn ml-2">Cancel</button>'
            );
        });
    
        $('table').on('click', '.submit-btn', function () {
          var tr = $(this).closest('tr');
          var id = parseInt(tr.attr('id'));
          var first_name = $('#first_name').val();
          var last_name = $('#last_name').val();
          var matric_number = $('#matric_number').val();
          console.log(id, first_name, last_name, matric_number);
    
          // Send a POST request to the server
          $.ajax({
            url: '/api/students',
            type: 'PUT',
            contentType: 'application/json',
            data: JSON.stringify({
              id: id,
              first_name: first_name,
              last_name: last_name,
              matric_number: matric_number
            }),
            success: function (response) {
              // Update the table with the new data
              tr.find('.first_name').text(first_name);
              tr.find('.last_name').text(last_name);
              tr.find('.matric_number').text(matric_number);
    
              // Change the Submit and Cancel buttons back to the Edit button
              $('.submit-btn')
                .parent()
                .html(
                  '<button class="btn btn-primary edit-btn">Edit</button>'
                );
            }
          });
        });
    
        $('table').on('click', '.cancel-btn', function () {
          var tr = $(this).closest('tr');

          // Get the original data
          var original = tr.data('original');
    
          // Revert the input fields back to text using the original data
          tr.find('.first_name').text(original.first_name);
          tr.find('.last_name').text(original.last_name);
          tr.find('.matric_number').text(original.matric_number);
    
          // Change the Submit and Cancel buttons back to the Edit button
          $(this)
            .parent()
            .html('<button class="btn btn-primary edit-btn">Edit</button>');
        });
      });
    </script>
  </body>
</html>